[MIKE]
URL = "http://192.168.178.58/cgi-bin/download.csv/"
PLOTNAME = "mike_pv_"
DB = "mike_raw_data.db"
WARNING = "50"
LIMIT_WECHSELRICHTER = 5000
PATH_DATA = "/home/mike/gh_projects/photovoltaik/"
PATH_PNG = "/home/mike/gh_projects/photovoltaik/png/"

    [MIKE.COLORS]
    BACKGROUND-COLOR = "#121212"
    BAR-COLOR = "azure"
    TEXT-COLOR = "ivory"


[HALLE]
URL = "http://192.168.178.199/cgi-bin/download.csv/"
PLOTNAME = "halle_pv_"
DB = "halle_raw_data.db"
WARNING = "50"
LIMIT_WECHSELRICHTER = 5000
PATH_DATA = "/home/halle/gh_projects/photovoltaik/"
PNG_PATH = "/home/halle/gh_projects/photovoltaik/png/"

    [HALLE.COLORS]
    BACKGROUND-COLOR = "#121212"
    BAR-COLOR = "aqua"
    TEXT-COLOR = "ivory"